version: "3"

services:
  web:
    image: "dreamingcodes/nest-festameucci"
    env_file:
      - .env
    environment:
      - "DB_HOST=mongo"
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
